language: ruby
rvm:
- 2.4.1
services:
- postgresql
before_script:
- psql -c 'create database olympic_api_test;' -U postgres
script:
- bundle exec rails db:reset db:setup db:migrate RAILS_ENV=test
- bundle exec rspec
